services:
  postgres:
    image: postgres:15.8
    container_name: postgres-15.8
    environment:
      POSTGRES_USER: minhyeok
      POSTGRES_PASSWORD: 1q2w3e4r
      POSTGRES_DB: sionic
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
